### ISSUE TITLE
Fix compatibility with Cinnamon 3.2

### ISSUE THREAD

**Issue by nv2k** [Feuerfuchs/GPaste-Reloaded-Cinnamon-Applet#6]
The applet it's currently not working with the latest version of Cinnamon, version 3.2.

It doesn't show anything when clicked in the toolbar.

Tested on ArchLinux.

**Comment by Feuerfuchs** [comment]
So I just installed Cinnamon 3.2 and the applet still works fine for me. Do you use the current version of the applet (2.2) and GPaste (3.22.0)?

**Comment by ikuria** [comment]
it's some kind of "direction"-problem: cinnamon-bar to the top = gpaste applet collapse downwards and works fine, but when the bar is on the bottom, the gpaste applet not collapsing upwards - nv2k can't see the applet because its collapsing always down (outside the desktop)
(ich denke ich hätte es auch auf deutsch beschreiben können, das hättest du sicher auch verstanden und für mich wäre es einfacher gewesen es zu erklären)

**Comment by Feuerfuchs** [comment]
@ikuria Egal, ich hab ja trotzdem verstanden was du meintest. ^^

Issue is solved with commit 1ca3bcc. I was using a custom PopupMenu class for some reason, so switching to Cinnamon's native class was the solution.
