### ISSUE TITLE
Applet not working

### ISSUE THREAD

**Issue by ricardojm** [Feuerfuchs/GPaste-Reloaded-Cinnamon-Applet#8]
I am using Debian 8 with cinnamon desktop environment.
I am able to use gpaste in command line. But the applet doesn't show in my botton panel.
Thanks

**Comment by Feuerfuchs** [comment]
Do you use the latest version of my applet, i.e. 2.5? If so, is there a message shown in the panel that GPaste is not installed?

**Comment by ricardojm** [comment]
Hello
Sorry I took too long to reply.
I'm using the 2.5 version and it doesn't show any message. Adding it to my panel, it doesn't show any icon.And at the applet menu, when I select to configure, nothing happens
Thanks

**Comment by Feuerfuchs** [comment]
Can you please post the contents of file `~/.cinnamon/glass.log` after you have added the applet to a panel?

**Comment by ricardojm** [comment]
Sure. Here:
error t=2017-05-16T16:57:05.297Z No JS module 'signalManager' found in search path
trace t=2017-05-16T16:57:05.297Z 
<----------------
@/home/ricardo/.local/share/cinnamon/applets/gpaste-reloaded@feuerfuchs.eu/applet.js:12
---------------->
error t=2017-05-16T16:57:05.297Z [Applet "gpaste-reloaded@feuerfuchs.eu"]: Error importing applet.js from gpaste-reloaded@feuerfuchs.eu
error t=2017-05-16T16:57:05.297Z Could not load applet gpaste-reloaded@feuerfuchs.eu

**Comment by Feuerfuchs** [comment]
Alright, that means there might be an issue with your Cinnamon installation. The SignalManager is part of Cinnamon and located in `/usr/share/cinnamon/js/misc/signalManager.js`. If Cinnamon can't find it, that means it either doesn't exist or it can't load it for some reason.

~~So what you can do is checking if the SignalManager file exists and check its permissions. If it doesn't exist or the permissions are correct, reinstalling Cinnamon might help. If nothing of that worked, you should file an issue in the Cinnamon repository because as far as I can tell, this problem is out of scope for me.~~

**Comment by Feuerfuchs** [comment]
So I just took a look at the file list of the Debian package `cinnamon-common`, and the SignalManager is missing in that list. I have no idea why that is, but considering the file is present in the corresponding Ubuntu package, this issue is related to the Debian repository.

**Comment by Feuerfuchs** [comment]
Forget what I wrote above. I just noticed the Cinnamon version in the Debian repos is **2**.2 instead of **3**.2, which is pretty old. It seems the SignalManager wasn't part of Cinnamon back then.

I rely on that component, though, so I guess you won't be able to use the applet. :/
